# Site settings
title:          Default
# description:    "blog ..."
baseurl:        ""
url:            "https://ssrssa.github.io/"

# Google Analytics
google_analytics: UA-131547672-1

# Author
author:
  name:         sssolll
  url:          https://ssrssa.github.io/
  email:        ssrssag@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Disqus
disqus_shortname: sssolll-github-io

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
